### ISSUE TITLE
how to play http/https online streaming?

### ISSUE THREAD

**Issue by cendolinside123** [sbooth/SFBAudioEngine#148]
is this library support for play http/https online streaming? If this library capable to play http/https online streaming can I get the example? Thank you

**Comment by sbooth** [comment]
Streaming via https is handled by `SFBHTTPInputSource` for the supported file formats. SimplePlayer has a minimal example for streaming.  Instead of a file URL pass a network URL to `SFBAudioPlayer` or `SFBAudioDecoder`.
