### ISSUE TITLE
How to use in existed project

### ISSUE THREAD

**Issue by Dearich** [sbooth/SFBAudioEngine#165]
Hello, please tell me how can I use your lib in my project. Thank you for your answer.

**Comment by Dearich** [comment]
I want to use your perfect lib in one existed project, I try to convert .ogg to .aac and play it. should I insert your lib like a framework ? Thank you

**Comment by sbooth** [comment]
Yes, a framework is the easiest way to use SFBAudioEngine. I just updated the project files today with universal targets.

**Comment by Dearich** [comment]
Thank you a lot. I will try to use it today.
