### ISSUE TITLE
Missing variable declaration (paramErr)?

### ISSUE THREAD

**Issue by edwellbrook** [sbooth/SFBAudioEngine#175]
Hey there!

Thanks so much for your work on SFBAudioEngine and for providing it as open source software. I'm still trying out the project but it looks ideal for my use case.

I've tried compiling the project (after some minor tweaks which I'll address separately) and have run into an issue around a missing variable declaration.

In some places throughout the project you use:

```objc
[NSError errorWithDomain:NSOSStatusErrorDomain code:paramErr userInfo:nil];
```

However `paramErr` is undefined.

After a search in the project and on GitHub as well (https://github.com/sbooth/SFBAudioEngine/search?q=paramErr), it seems the value isn't provided anywhere.

 - Is this something that should be provided by the consumer of the library? If so, how?
 - Is this something that is missing from the project itself? If so, please suggest a fix and I'll happily open a PR.
 - Is this something that I've misconfigured or misunderstood? What would be useful information I can offer to help you point me in the right direction?

Thanks!

**Comment by edwellbrook** [comment]
Looking into this a little further, it seems the project compiles correctly for macOS, however the missing variable errors appear only on iOS.

I can see `paramErr` is a constant, and by `@import`ing `CoreServices` in the files where we reference these errors the problem goes away.

I'll shortly open a PR to include an import to `CoreServices`.

Separately to this, do you have any plans to set up CI / some automated testing for PRs? Would love to make sure the project continues to compile correctly for iOS going forward.

Thanks!

**Comment by edwellbrook** [comment]
Quick update, importing CoreServices on iOS doesn't actually solve the problem. `paramErr` and `ioErr` are part of `Carbon` and aren't available on iOS (as far as I know).

Given that — should how would you suggest I approach fixing this?

**Comment by sbooth** [comment]
I didn't realize that all of those (old) error codes were deprecated. I just merged a PR that removes their use.

I'd like to implement CI of some sort but I've run into problems compiling all the dependencies. I do build manually before merging PRs but in this case it seems something slipped through the cracks.
