### ISSUE TITLE
Dithering when playing DSD in PCM mode while iPhone screen is locked

### ISSUE THREAD

**Issue by pzs7602** [sbooth/SFBAudioEngine#187]
Playing DSD audio in PCM mode is dithering when iPhone screen is locked, change maximumFramesPerSlice to 4096(https://github.com/sbooth/SFBAudioEngine/issues/22) could not solve this.
Playing DSD audio in DoP mode and other format audio files are normal when iPhone screen is locked(change maximumFramesPerSlice to 4096).

**Comment by sbooth** [comment]
So the issue only seems to affect `SFBDSDPCMDecoder` instances and no other `SFBAudioDecoder` subclasses? That's odd to be sure.

**Comment by pzs7602** [comment]
Yes in my test case, maybe  you should have a try to ensure this.
