### ISSUE TITLE
MAC_SDK_613.zip no longer available. 

### ISSUE THREAD

**Issue by jtoronto** [sbooth/SFBAudioEngine#193]
The makefile tries to download 613 which is no longer available. I tried editing the makefile for MAC_SDK_614.zip however when it runs I get this error. 

`patching file MAC_SDK-src/Source/Shared/All.h
Hunk #1 FAILED at 49.
1 out of 1 hunk FAILED -- saving rejects to file MAC_SDK-src/Source/Shared/All.h.rej
make: *** [angle_bracket_include.patched] Error 1`

**Comment by sbooth** [comment]
I wish the old downloads weren't removed once they're no longer the current version.
