### ISSUE TITLE
Build fails, unable to download MAC_SDK_620.zip from Monkey's Audio

### ISSUE THREAD

**Issue by gregggreg** [sbooth/SFBAudioEngine#195]
If you clone this repo (and submodules) and try to make the frameworks, it will fail when it is unable to download MAC_SDK_620.zip from monkeyaudio.com. If you look in the directory, this file is no longer available and there are only files with higher build numbers there.

**Comment by sbooth** [comment]
Similar to https://github.com/sbooth/AudioXCFrameworks/pull/20
