### ISSUE TITLE
Please clarify the best way to include this project in an app for multiple devs/workstations

### ISSUE THREAD

**Issue by svenoaks** [sbooth/SFBAudioEngine#201]
I have successfully followed the build instructions, then I dragged the SFBAudioEngine.xcodeproj into my app, and added the SFBAudioEngine.framework as an Embedded Content item to the app target. This has worked fine, I can use the library in my project.

However, it's a cloned repo with submodules that has to be built. It seems like it's difficult/cumbersome to set up on other machines.

Is there an easier way to include it my project, that a simple git pull of my app project from another machine would work to get it working there?

**Comment by sbooth** [comment]
I agree that the project is challenging to incorporate. Hopefully the resolution of #200 will resolve this as well.

**Comment by sbooth** [comment]
Could you take a look #230 to see if it adequately addresses the issue?
