### ISSUE TITLE
mpg123 header includes seemingly using incorrect include type

### ISSUE THREAD

**Issue by NattyNarwhal** [sbooth/SFBAudioEngine#207]
After a fresh clone + build of XCFrameworks, when trying to build both SFBAudioEngine directly or the Mac SimplePlayer, there's the following error:

`/Users/calvin/Library/Developer/Xcode/DerivedData/SimplePlayer-macOS-edevwanlfzmwoecqwirlxhdxzcps/Build/Products/Debug/mpg123.framework/Headers/mpg123.h:12:10: Double-quoted include "fmt123.h" in framework header, expected angle-bracketed instead`

It seems the `<fmt123.h>` needs to be in double quotes instead. There's still a warning, but it's no longer an error. My uglo workaround is: `find . -name mpg123.h -exec gsed -i 's/<fmt123.h>/"fmt123.h"/g' {} \;`

**Comment by sbooth** [comment]
I believe either `<mpg123/fmt123.h>` or `"fmt123.h"` would be an improvement but I'm inclined toward the former.

**Comment by sbooth** [comment]
Should be fixed in https://github.com/sbooth/AudioXCFrameworks/commit/d1f7ec110172ffe6c97476c9b64462d2cf5b6a83
