### ISSUE TITLE
Issues with building macOS Sample Player

### ISSUE THREAD

**Issue by capaldo** [sbooth/SFBAudioEngine#208]
After following the build instructions in the README, I run into the following errors when building the frameworks/project:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/41103209/162499457-5df3b4c4-64c7-4b2c-99b5-dc1a7ffe010f.png">

**Comment by sbooth** [comment]
I believe the latest update to the `XCFrameworks` submodule fixes this issue.
