### ISSUE TITLE
The opus file is seriously distorted, and only one side of the speaker has sound.

### ISSUE THREAD

**Issue by mytianer** [sbooth/SFBAudioEngine#215]
I used the demo to test it again, it is true

**Comment by sbooth** [comment]
Just to confirm, is this for all opus files or only those generated with SFBAudioEngine?

**Comment by mytianer** [comment]
It's for all opus file,  when use foobar it play well, it should be a problem with decoding

**Comment by sbooth** [comment]
Please try out the proposed fix and let me know if it works.
