### ISSUE TITLE
When the speex file is playing, only one side of the speaker has sound, and SFBAudioPlayer.totalTime is nil

### ISSUE THREAD

**Issue by mytianer** [sbooth/SFBAudioEngine#216]

**Comment by sbooth** [comment]
I believe I've fixed the stereo decoding problem in #217. If you're able to test the proposed fix I'd appreciate it.

**Comment by mytianer** [comment]
I just tested it and the stereo works fine

**Comment by mytianer** [comment]
> I believe I've fixed the stereo decoding problem in #217. If you're able to test the proposed fix I'd appreciate it.

I just tested it and the stereo works fine

**Comment by sbooth** [comment]
Thanks for testing out the stereo fix.

Calculating the total number of frames in the stream will require a bit of work so I've opened a separate issue for it.
