### ISSUE TITLE
I keep getting an error when converting to apple native format, like m4a aac

### ISSUE THREAD

**Issue by mytianer** [sbooth/SFBAudioEngine#218]
It's the same whether I use AudioConverter.convert(file.url, to: targetUrl) or AudioConverter.convert(file.url, using: customEncoder). I have set the relevant parameters of SFBCoreAudioEncoder

**Comment by sbooth** [comment]
Could you give more information on the input format, output format, and encoder settings?

**Comment by mytianer** [comment]
> Could you give more information on the input format, output format, and encoder settings?

The input format is any audio.

I use these parameters when converting to m4a:
kAudioFileM4AType,
kAudioFormatMPEG4AAC,
 kAudioConverterSampleRateConverterComplexity_Normal,
kAudioConverterQuality_Medium,
kAudioConverterCodecQuality = 1,
kAudioConverterEncodeBitRate = 192000

**Comment by sbooth** [comment]
I can confirm there is a `paramErr` when setting `kExtAudioFileProperty_ClientDataFormat` at https://github.com/sbooth/SFBAudioEngine/blob/91c754ceb3304a120ee68ce06aaf60f604ce6a04/Encoders/SFBCoreAudioEncoder.mm#L410
