### ISSUE TITLE
SFBFLACDecoder - decodeIntoBuffer - not decoding all frames

### ISSUE THREAD

**Issue by BTRLabs** [sbooth/SFBAudioEngine#250]
This is only related to FLAC files and the `SFBFLACDecoder`, as no other SFB*Decoder has this issue.

Based on the following swift code, which is simply an example to prove a point, the `print("WARNING...")` is always executed.  And listening to what is playing, there is definitely audio missing.  The missing frame count ranges from as little as 140 missing frames to as much as 4096 frames across a set of tested FLAC files.  All FLAC files have been verified using `flac -t "file.flac"`.

``` swift
do {
  let decoder = try AudioDecoder(url: URL("file.flac"))
  try decoder.open()
  let durationOfChunkToRead : TimeInterval = 1
  try decoder.seek(to: decoder.length - AVAudioFramePosition(decoder.processingFormat.sampleRate * durationOfChunkToRead))
  try decoder.decode(into: decodedBuffer)
  if decoder.inputSource.atEOF && decoder.position < decoder.length {
    print("WARNING - inputSource.atEOF is TRUE while decoder.position < decoder.length by \(decoder.length - decoder.position) frames")
  }
} catch {
  print(error.localizedDescription)
}
```
Have attempted to debug and fix, but without luck.

Thoughts??

**Comment by sbooth** [comment]
Could you check out the proposed fix in #252 and see if it works for you?

**Comment by BTRLabs** [comment]
Yes, #252 in conjunction with using libFLAC 1.4.2 fixed the issue.  Amazing turnaround.  Thanks!

**Comment by sbooth** [comment]
I'm glad it's working now. Thanks for reporting this issue!
