### ISSUE TITLE
Importing Package

### ISSUE THREAD

**Issue by EugeneTheGreat** [sbooth/SFBAudioEngine#262]
Hi,

I am a student who needs the library for my assignment to develop an iOS 16 application on a M1 machine with the latest xCode. I was just wondering is there a detailed guide to import the library to xcode or add the package dependencies as I am new to iOS dev. From the repo readme file, I have tried to clone the repo and add the embed XCFrameworks in xcode but I am not able to find the SFBAudioEngine.framework in the cloned folder. I am a little lost and unsure how to continue. 

I really appreciate in advance for any help given. 

Thank you.

**Comment by sbooth** [comment]
If you follow the three preparatory steps in the [README](https://github.com/sbooth/SFBAudioEngine#building-sfbaudioengine) and then issue `make` from the same directory you should end up with an XCFramework in that dir that you can drag to your project's folder and then add it as a dependency.

**Comment by EugeneTheGreat** [comment]
Alright. Thank you very much!
