### ISSUE TITLE
macOS 14+ dependencies?

### ISSUE THREAD

**Issue by drkameleon** [sbooth/SFBAudioEngine#268]
I've come across this project and was excited to use it (seeing that it supported 10.13+), but after trying to build the framework (I tried with the `make` command and via Xcode too), it seems like it keeps coming across symbols and constants that appeared after macOS 13 (I'm running Ventura).

**For example:**

<img width="422" alt="Screenshot 2023-10-03 at 16 57 26" src="https://github.com/sbooth/SFBAudioEngine/assets/1265028/6bd634ac-c5e4-4c5e-a86c-70ae7795c977">

Is there any workaround around that, that I may be missing?

Thanks! (and congratulations on the project! 😉 )

**Comment by sbooth** [comment]
It seems that the voice activity constants were introduced in macOS 14 but aren't decorated with availability information. I'm not sure if that is an oversight or if Apple doesn't typically do that for non-deprecated constants. I will look into either adding availability decorations or defining them manually if they're missing.

**Comment by sbooth** [comment]
What Xcode version are you using?

**Comment by drkameleon** [comment]
Thanks! :)

> What Xcode version are you using?

14.3.1 (14E300c)

**Comment by sbooth** [comment]
Are you able to upgrade to Xcode 15? It requires macOS 13.5 or later. That would fix your issue.

**Comment by drkameleon** [comment]
> Are you able to upgrade to Xcode 15? It requires macOS 13.5 or later. That would fix your issue.

Nice idea! I'll give it a try and will let you know. :) (Apparently, the 13.6 update is still available - not really sure I'll make the leap of faith to Sonoma, yet)

**Comment by drkameleon** [comment]
So... update:

your suggestion was literally spot on! I upgraded macOS to 13.6 (which was quite long due already) and also Xcode to v15.

It all works beautifully! Thanks! :)
