### ISSUE TITLE
AudioDevice

### ISSUE THREAD

**Issue by CHETANSINHZALA** [sbooth/SFBAudioEngine#282]
Cannot find type 'AudioDevice' in scope

I am using this and last night i reclone it and getting above error .
<img width="265" alt="Screenshot 2023-12-29 at 12 10 09 AM" src="https://github.com/sbooth/SFBAudioEngine/assets/20256356/895bb757-df5a-482a-9361-825657b5b269">

**Comment by sbooth** [comment]
That portion of `SFBAudioEngine` was refactored into [CAAudioHardware](https://github.com/sbooth/CAAudioHardware).

**Comment by sbooth** [comment]
@CHETANSINHZALA is this issue resolved?

**Comment by CHETANSINHZALA** [comment]
yes
Thank you.
