### ISSUE TITLE
Issues queueing and dequeueing Opus tracks

### ISSUE THREAD

**Issue by fig7** [sbooth/SFBAudioEngine#291]
I am writing my own music player for MacOS and I am using the SFBAudioEngine for playback. It is working very well for me so far.

My player always queues the next track when the audio player indicates that a track is now playing (in audioPlayerNowPlayingChanged()). This works just fine if all the tracks are mp3/vorbis or if they are all opus.

But when my playlist mixes opus and mp3 (or vorbis) tracks, there are problems.

One of two things happen next:

1. The player unexpectedly transitions between paused and playing before playing the opus track. Then, when the opus track finishes playing, it unexpectedly transitions between playing and paused, leaving my player thinking that playback is paused (which it isn't). I am using audioPlayerPlaybackStateChanged() to observe the state of the player.

2. Sometimes, the player simply fails to dequeue the opus track, and playback stops.

I have done a little bit of debugging and I think these things happen because opus needs a different audio node, so the player has to switch between audio nodes, and that's when things go wrong. Now that I think about it, I wonder if the unexpected player states come from the "other audio node". The second issue doesn't happen as often, but it's really annoying when it does! 

NB. This is on a Mac M1 Mini running MacOS 14.

**Comment by fig7** [comment]
Simpler example (maybe the same problem):

If I do the following, I get the same "decoder doesn't dequeue" result:

        try player.enqueue(opusURL)
        try player.play()

There is no exception or log output. The only thing you do get is the playback state callback which is .playing

By contrast, "try player.play(opusURL)" works just fine.

**Comment by fig7** [comment]
I am debugging this now, so I will try to get some more information. I have seen it stop going from opus to vorbis now, too.
I've only had it stop playing once so far. In that case, the new decoder somehow got cancelled before it had a chance to get going.

**Comment by fig7** [comment]
I haven't tried. I will have a look at the SimplePlayer tomorrow. I don't know what the sample rates of the files are, but I can check that too. It's quite possible that the sample rates differ. Some of my music I have ripped from CDs, but other tracks were downloaded. I've got mp3s, m4as, oggs, and some flac too. It's all a bit of a mix.

**Comment by fig7** [comment]
I can confirm that SimplePlayer has the same problem. My Opus tracks are 48KHz and most of my other tracks are 44.1KHz. The EndOfAudio notification gets called twice. The first call dequeues the next decoder and the second call cancels it. This doesn't happen every time, but it happens often enough to reproduce it easily. Full log from when it goes wrong:

Render block format: <AVAudioFormat 0x600001e48140:  2 ch,  48000 Hz, Float32, deinterleaved>
Decoder thread starting
AVAudioMixerNode input sample rate (48000.00 Hz) and output sample rate (44100.00 Hz) don't match
↑ rendering: <AVAudioFormat 0x600001e48140:  2 ch,  48000 Hz, Float32, deinterleaved>
← main mixer out: <AVAudioFormat 0x600001e55680:  2 ch,  44100 Hz, Float32, deinterleaved>
Enqueuing "Damned If I Do.opus"
Dequeued decoder for "Damned If I Do.opus"
Processing format: <AVAudioFormat 0x600001e48230:  2 ch,  48000 Hz, Float32, interleaved>
Decoding started for "Damned If I Do.opus"
Rendering will start in 11.84 msec for "Damned If I Do.opus"
Rendering started notification for "Damned If I Do.opus" arrived 1.08 msec late
Insufficient audio in ring buffer: 473 frames available, 557 requested
Decoding complete for "Damned If I Do.opus"
Rendering will complete in 20.47 msec for "Damned If I Do.opus"
End of audio in 22.45 msec
Collecting decoder for "Damned If I Do.opus"
Insufficient audio in ring buffer: 369 frames available, 557 requested
End of audio in 19.42 msec
Rendering complete notification for "Damned If I Do.opus" arrived 1.36 msec late
End of audio notification arrived 1.15 msec late
Render block format: <AVAudioFormat 0x600001ee01e0:  2 ch,  44100 Hz, Float32, deinterleaved>
Decoder thread starting
↑ rendering: <AVAudioFormat 0x600001ee01e0:  2 ch,  44100 Hz, Float32, deinterleaved>
Enqueuing "Love Is A Wonderful Colour.ogg"
Dequeued decoder for "Love Is A Wonderful Colour.ogg"
Processing format: <AVAudioFormat 0x600001ee01e0:  2 ch,  44100 Hz, Float32, deinterleaved>
Decoding started for "Love Is A Wonderful Colour.ogg"
End of audio notification arrived 1.35 msec late
Canceling decoding for "Love Is A Wonderful Colour.ogg"
Collecting decoder for "Love Is A Wonderful Colour.ogg"

**Comment by sbooth** [comment]
Something is definitely amiss. I think the initial problem occurred earlier based on the log message of input and output sample rate mismatch, which shouldn't really happen. If you can post a full log from app launch to when the problem occurs it might be helpful.

Are you letting the tracks play through or are you starting and stopping the player, seeking, etc? Do you have a reliable way to reproduce the problem?

Unfortunately I don't have an M1 Mac to test with although I'm not sure it would make a difference. What is the output device and sample rate?

**Comment by sbooth** [comment]
Please try out the change in #292 which should fix the problem.

Thanks for the bug report!

**Comment by fig7** [comment]
As far as I can tell, everything is working perfectly for me now. The issue I was seeing with the player state events (from audioPlayerPlaybackStateChanged()) was a bug in my code. The less said about that the better!
