### ISSUE TITLE
MOD files repeat endlessly

### ISSUE THREAD

**Issue by fig7** [sbooth/SFBAudioEngine#299]
I have a few mod files that I downloaded a long time ago. I noticed that they repeat instead of stopping when they get to the end.

When playback should stop there is a log message in the console that says:
duh_render_int() returned short frame count: requested 512, got 256

According to Audio Overload my files are:
Amiga *Tracker (.mod) files, subtype ProTracker or subtype ProTracker/NoiseTracker

NB: The reported track length appears to be correct

**Comment by sbooth** [comment]
Could you share one of the files either by posting or emailing me a link?

**Comment by fig7** [comment]
Here is one example:
https://modarchive.org/index.php?request=view_by_moduleid&query=167162

I have just noticed that their "Play with Online Player" also loops the track, so I guess it's just a problem with the decoder.

**Comment by sbooth** [comment]
Thanks for reporting this. Could you try the changes in #300 and see if they work for you?

**Comment by fig7** [comment]
My 5 mod files all play just fine with the change. Many thanks. I should go away and download some more!
