### ISSUE TITLE
Package framework  BUG in the background

### ISSUE THREAD

**Issue by lanshanzhao** [sbooth/SFBAudioEngine#347]
When i use the package version,i add the background and lock screen to the code, the play is not smooth, it come's the bug  under this.please fix it.

`AVAudioEngine output format changed from <AVAudioFormat 0x300982a80:  2 ch,  48000 Hz, Float32, deinterleaved> to <AVAudioFormat 0x30096cdc0:  2 ch,  44100 Hz, Float32, deinterleaved>
↑ rendering: <AVAudioFormat 0x3009b6210:  2 ch,  44100 Hz, Float32, deinterleaved>
Received AVAudioEngineConfigurationChangeNotification
AVAudioEngine output format changed from <AVAudioFormat 0x30098fc50:  2 ch,  48000 Hz, Float32, deinterleaved> to <AVAudioFormat 0x3009555e0:  2 ch,  44100 Hz, Float32, deinterleaved>
↑ rendering: <AVAudioFormat 0x3009dc640:  2 ch,  44100 Hz, Float32, deinterleaved>
Insufficient audio in ring buffer: 2118 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
Insufficient audio in ring buffer: 2048 frames available, 4096 requested
、

**Comment by sbooth** [comment]
Please try the latest version of the `main` branch and also see https://github.com/sbooth/SFBAudioEngine/discussions/343 which might help.

**Comment by sbooth** [comment]
If this is still a problem with version 0.2.0 please reopen this issue with the details.

**Comment by lanshanzhao** [comment]
ok,i will try it
