### ISSUE TITLE
[App Store Connect] Asset validation failed /Frameworks/FLAC.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString.

### ISSUE THREAD

**Issue by Volodymyr-13** [sbooth/SFBAudioEngine#375]
Hey!
I'm unable to submit a new build of my app because App Store Connect is throwing this error:

Asset validation failed
The bundle 'Payload/____.app/Frameworks/FLAC.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring (ID: 9b211549-3c2d-4aad-84ba-ced0b82d0c53)

![Screenshot](https://github.com/user-attachments/assets/4dc649f5-b72b-4828-af18-d25847395fd5)

Using: 

- **master** branch of SFBAudioEngine
-  Xcode 16.1
- IPHONEOS_DEPLOYMENT_TARGET = 17.0; (**mandatory** requirement for my project)

p.s. @sbooth Stephen  to be honest - this is urgent for me.. have to submit asap to release some hotfix bugs.. is there any chance you could look at this

**Comment by sbooth** [comment]
I will take a look at this as soon as I can but it might not be today. If you need an immediate fix you can always build the FLAC framework yourself and use a local package.

**Comment by Volodymyr-13** [comment]
> I will take a look at this as soon as I can but it might not be today. If you need an immediate fix you can always build the FLAC framework yourself and use a local package.

Hmm, that's what I'm trying to figure out how to do. It's for all other platforms too, but what should I add, like an info.plist file with some version in each one? Also, how do I release these(in GitHub release as version or ... many questions..)? I'm completely confused and have no idea how to do this.

**Comment by sbooth** [comment]
https://github.com/sbooth/AudioXCFrameworks/pull/92 will fix this problem once it's merged and the binary frameworks are updated.

**Comment by Volodymyr-13** [comment]
> [sbooth/AudioXCFrameworks#92](https://github.com/sbooth/AudioXCFrameworks/pull/92) will fix this problem once it's merged and the binary frameworks are updated.

Thanks, but when this will be merged into SFBAudioEngine? I'm using SFBAudioEngine-> master for now, or maybe this will be a release 0.4?
