### ISSUE TITLE
v0.4.0 previously worked - Assigning to 'uint32_t' (aka 'unsigned int') from incompatible type 'std::optional<unsigned int>' 

### ISSUE THREAD

**Issue by Volodymyr-13** [sbooth/SFBAudioEngine#397]
I was successfully using the v0.4.0 release, but today, just after cleaning the cache of SPM, I encountered this error:

![Screenshot](https://github.com/user-attachments/assets/2d08d830-cd40-4460-bac7-b12bed651b20)

I created a test project by adding the version 0.4.0, but I still encountered the same error. It's quite strange that after some time, the release stopped working. 

But using **main** branch "fixes" this.

**Comment by sbooth** [comment]
SPM probably updated `CXXAudioUtilities` to the newest version which has a few breaking changes. The versions of the dependencies specified in `Package.resolved` are the versions I tested the release with and should work. Newer minor/patch versions "should" work, but I don't strictly adhere to semantic versioning for versions less than 1.0 so there is no guarantee.

**Comment by Volodymyr-13** [comment]
Yep, that was my idea too, but I don't understand how this is possible if for 0.4.0 which I used before. 

```
dependencies: [
	.package(url: "https://github.com/sbooth/CXXAudioUtilities", from: "0.1.0"),
```

Okay, the latest CXXAudioUtilities is **0.1.2**, but 0.4.0 is not using it.. so how.. it worked since I've added 0.4.0, but now if you create a new project and add it into, it wont.
