### ISSUE TITLE
Random exception in MP4Metadata.cpp

### ISSUE THREAD

**Issue by jwells89** [sbooth/SFBAudioEngine#51]
In my program I'm seeing exceptions seemingly thrown at random when creating metadata objects from files. As far as I can see there's nothing that ties the files that it throws on together and it occurs rarely enough that it only shows up when processing many files in sequence (typically it only appears when processing upwards of 500 songs, but occasionally this isn't true). The tag it always triggers on is kMusicBrainzReleaseIDKey, as seen below.

![screen shot 2014-12-10 at 5 15 18 pm](https://cloud.githubusercontent.com/assets/5009493/5387581/352b07f0-8091-11e4-8b5d-5917dac048e9.png)

I pulled and recompiled a fresh version of SFBAudioEngine and its dependencies yesterday and to the best of my knowledge, nothing is getting prematurely released in my own code, so I'm not sure what the problem could be.

**Comment by sbooth** [comment]
My long-term solution for this is to improve TagLib's mp4 support and migrate to that from mp4v2.

**Comment by sbooth** [comment]
I believe this is fixed in 21331d44e06bb805d877a889f368f4ea19335803
