### ISSUE TITLE
'wavpack/wavpack.h' file not found when compiling for iOS

### ISSUE THREAD

**Issue by horaceho** [sbooth/SFBAudioEngine#52]
![screen shot 2015-02-04 at 17 32 30](https://cloud.githubusercontent.com/assets/6657/6037994/3e88710a-ac94-11e4-8902-6b2af0881aca.png)

The `wavpack.h` is  inside `Libraries/ios-simulator-clang-libc++/include/wavpack` folder but there is an error as shown above.

**Comment by sbooth** [comment]
I assume you're building for the simulator and not for the device?

**Comment by horaceho** [comment]
I built for device.

**Comment by sbooth** [comment]
This is related to issue #50
