### ISSUE TITLE
SFBAudioEngine used in Swift project

### ISSUE THREAD

**Issue by pzs7602** [sbooth/SFBAudioEngine#53]
I use SFBAudioEngine in my Swift project, since Swift can use C/C++ codes directly, I define a Objective C class wrapper for AudioPlayer:
```
#import <Foundation/Foundation.h>

@interface AudioPlayerWrapper : NSObject{
}
- (id) init;
- (void) playPause;
- (void) seekForward;
- (void) seekBackward;
- (BOOL) playURL:(NSURL *)url;
- (BOOL) isPlaying;
- (BOOL) isPaused;
- (BOOL) isStopped;
- (BOOL) stop;

@end

#import "AudioPlayerWrapper.h"
#include "AudioPlayer.h"
#include "AudioDecoder.h"
#include "Logger.h"

enum ePlayerFlags : unsigned int {
    ePlayerFlagRenderingStarted			= 1u << 0,
    ePlayerFlagRenderingFinished		= 1u << 1
};

@interface AudioPlayerWrapper(){
    SFB::Audio::Player	*_player;
    std::atomic_uint	_playerFlags;
}
@end

// AudioPlayerWrapper.m
@implementation AudioPlayerWrapper
- (id) init
{
    self = [super init];
    if (self){
        _player = new SFB::Audio::Player();
        // This will be called from the realtime rendering thread and as such MUST NOT BLOCK!!
        _player->SetRenderingStartedBlock(^(const SFB::Audio::Decoder& /*decoder*/){
            _playerFlags.fetch_or(ePlayerFlagRenderingStarted);
        });
        
        // This will be called from the realtime rendering thread and as such MUST NOT BLOCK!!
        _player->SetRenderingFinishedBlock(^(const SFB::Audio::Decoder& /*decoder*/){
            _playerFlags.fetch_or(ePlayerFlagRenderingFinished);
        });
        NSLog(@"player created");
        asl_add_log_file(nullptr, STDERR_FILENO);
        ::SFB::Logger::SetCurrentLevel(::SFB::Logger::debug);
    }
    return self;
}

- (void) playPause
{
    _player->PlayPause();
}

- (void) seekForward
{
    _player->SeekForward();
}

- (void) seekBackward
{
    _player->SeekBackward();
}

- (void) seek:(SInt64)position
{
    
    SInt64 totalFrames;
    if(_player->GetTotalFrames(totalFrames)) {
        SInt64 desiredFrame = (SInt64)(position * totalFrames);
        _player->SeekToFrame(desiredFrame);
    }
}

- (BOOL) playURL:(NSURL *)url
{
    if(nil == url)
        return NO;
    return _player->Play((__bridge CFURLRef)url);
}
.....
```

In Swift, play a flac audio file:
self.myAudioPlayer = AudioPlayerWrapper()
let audioFileURL = NSURL(fileURLWithPath: NSBundle.mainBundle().pathForResource("test", ofType: "flac")!)
self.myAudioPlayer!.playURL(audioFileURL)

the above code fail to play the flac file. I found the AudioDecoder is not created successfully:
![2015-04-26 10 42 40](https://cloud.githubusercontent.com/assets/2361197/7335673/060dbcac-ec01-11e4-89c6-5adfde086c0f.png)

do I need to register the supported audio decoder(FLAC,APE,...) before playing?
thanks!

**Comment by sbooth** [comment]
You don't need to register the decoder subclasses- they are registered automatically at static initialization time.

I see your file is located in the `Containers` directory.  Is this a sandboxed app?  Perhaps `powerboxd` is denying access?

**Comment by pzs7602** [comment]
modify AudioPlayer.cpp as follows:

bool SFB::Audio::Player::Play(CFURLRef url)
{
	if(nullptr == url)
		return false;

//	auto decoder = Decoder::CreateForURL(url);
    // modify above line to:
    SFB::CFString extension = CFURLCopyPathExtension(url);
    Decoder::unique_ptr decoder;
    if(kCFCompareEqualTo == CFStringCompare(extension, CFSTR("flac"), kCFCompareCaseInsensitive)){
        decoder = FLACDecoder::CreateDecoder(InputSource::CreateForURL(url));
    }
    else if(kCFCompareEqualTo == CFStringCompare(extension, CFSTR("ape"), kCFCompareCaseInsensitive)){
        decoder = MonkeysAudioDecoder::CreateDecoder(InputSource::CreateForURL(url));
    }
    else if(kCFCompareEqualTo == CFStringCompare(extension, CFSTR("tta"), kCFCompareCaseInsensitive)){
        decoder = TrueAudioDecoder::CreateDecoder(InputSource::CreateForURL(url));
    }
    else if(kCFCompareEqualTo == CFStringCompare(extension, CFSTR("ogg"), kCFCompareCaseInsensitive)){
        decoder = OggVorbisDecoder::CreateDecoder(InputSource::CreateForURL(url));
    }
    else if(kCFCompareEqualTo == CFStringCompare(extension, CFSTR("wv"), kCFCompareCaseInsensitive)){
        decoder = WavPackDecoder::CreateDecoder(InputSource::CreateForURL(url));
    }
    else if(kCFCompareEqualTo == CFStringCompare(extension, CFSTR("aiff"), kCFCompareCaseInsensitive)){
        LOGGER_DEBUG("org.sbooth.AudioEngine.Player", "create sndfile decoder");
        decoder = LibsndfileDecoder::CreateDecoder(InputSource::CreateForURL(url));
    }
    else{
        decoder = Decoder::CreateForURL(url);
    }
	return Play(decoder);
}

then the audio file(flac/ape/wavpack/...) can be played. don't know why.

**Comment by sbooth** [comment]
If you step through `Decoder::CreateURL()` can you determine where the failure occurs?

**Comment by pzs7602** [comment]
Still can't determine where the failure occurs, the decoder returned by original code is not NULL.
![2015-05-07 10 35 18](https://cloud.githubusercontent.com/assets/2361197/7507689/4c55164e-f4a6-11e4-876d-44cc649e8ee2.png)

BTW, how to set the volume of the audio player?
thanks.

**Comment by sbooth** [comment]
Setting the player volume is slightly clunky.  If you're using the core audio output:

```
auto& output = dynamic_cast<SFB::Audio::CoreAudioOutput&>player->GetOutput();
output.SetVolume(0.8);
```

Obviously this is C++ so to do this from Swift you would need to add some code to your `AudioPlayerWrapper` class.

**Comment by sbooth** [comment]
Is this still an problem? I'd like to close this issue if not.
