### ISSUE TITLE
Musepack not updated in dependencies

### ISSUE THREAD

**Issue by jameshurst** [sbooth/SFBAudioEngine#54]
As of https://github.com/sbooth/SFBAudioEngine/commit/9b66b69ce74deaa6cf496c51b04cb9ba512f91c4 musepack was updated to r475 but it seems that this update to musepack was never reflected in the dependencies archive linked in the README. Trying to build right now results in `mpc/mpcdec.h` not being found.

**Comment by wang0109** [comment]
Yes, same error here. I changed mpcdec to mpc and it builds ok.

**Comment by notjosh** [comment]
I took a stab at updating the dependency generator. If you're working with OS X, take a look over at https://github.com/sbooth/AudioFrameworks/pull/7 and try building 'em yourself. That's building fine for me on master, so hopefully you also!
