### ISSUE TITLE
DSFDecoder failed to decode .dsf file

### ISSUE THREAD

**Issue by pzs7602** [sbooth/SFBAudioEngine#55]
when I play a .dsf audio file downloaded from 
http://samplerateconverter.com/content/free-samples-dsf-audio-files

- (IBAction) playTestTrack:(id)sender
{
	if(![self playURL:[[NSBundle mainBundle] URLForResource:@"test" withExtension:@"dsf"]])
		LOGGER_ERR("org.sbooth.SimplePlayer-iOS", "Could not play");
}

the following message displayed in console and the audio file could not be played:

<Error>: Format not supported: 2 ch, 2.8224e+06 Hz, 'DSD ' (0x00000020) 1 bits/channel, 1 bytes/packet, 8 frames/packet, 0 bytes/frame
May 23 00:28:53 pzsip6p SimplePlayer-iOS[607] <Error>: Could not play

does DSFDecoder require some specified format DSF audio file?
thanks!

**Comment by sbooth** [comment]
The DSF decoder doesn't require a specific DSF format but the DSD and DSF decoders only work with ASIO output which is currently only supported for exaSound DACs.  The DSF and DSD decoders produce raw DSD output which cannot be handled by Core Audio without wrapping in PCM using the DoP (DSD over PCM) decoder.  I think you probably want to use the `DoPDecoder` class for this purpose, which will send PCM wrapped DSD to DACs that support it.

**Comment by sbooth** [comment]
One thing to add: there is currently no functionality to convert DSD to PCM for general use.

**Comment by pzs7602** [comment]
where can I find asiosys.h and other relative header files?
thanks a lot!

**Comment by sbooth** [comment]
They are part of the ASIO SDK from Steinberg.  You can download it from http://www.steinberg.net/en/company/developers.html

**Comment by pzs7602** [comment]
Hi Stephen, thanks for your help!
I can decode DSF file now by using DoPDecoder(I use SFBAudioEngine-iOS project download from this site and when tap "Play Test Track" button, playing time and progress slider go correctly), but there is no sound at all(seems some noise there), do I need to set output for the player?

**Comment by sbooth** [comment]
Are you using a DAC that supports DoP?

**Comment by pzs7602** [comment]
No, I just want to play dsf/dff audio file in iOS by using SFBAudioEngine, is that possible?

**Comment by sbooth** [comment]
No this currently isn't possible; SFBAudioEngine doesn't perform DSD to PCM conversion.
