### ISSUE TITLE
How DoPDecoder works with ASIO to output to DAC?

### ISSUE THREAD

**Issue by pzs7602** [sbooth/SFBAudioEngine#56]
I have a Sony PHA-3 DAC supporting DoP input, I know I can use DoPDecoder with ASIO output to produce DoP data and send them to PHA-3, but how DoPDecoder be used with ASIO ? Please help me, Thanks!

**Comment by sbooth** [comment]
ASIO output only works with certain exaSound DACs and requires special drivers.  You should be able to use a `DoPDecoder` with the standard core audio output as long as the equalizer is flat.

**Comment by pzs7602** [comment]
I modify the codes in AudioPlayer.cpp for using DoPDecoder when playing .dsf audio file:

bool SFB::Audio::Player::Play(CFURLRef url)
{
	if(nullptr == url)
		return false;

//	auto decoder = Decoder::CreateForURL(url);
    SFB::CFString extension = CFURLCopyPathExtension(url);
    Decoder::unique_ptr decoder;
    if(kCFCompareEqualTo == CFStringCompare(extension, CFSTR("dsf"), kCFCompareCaseInsensitive)){
        std::cout << "dsf decoder";
        decoder = DoPDecoder::CreateForURL(url);
    }
    else if(kCFCompareEqualTo == CFStringCompare(extension, CFSTR("ape"), kCFCompareCaseInsensitive)){
        decoder = MonkeysAudioDecoder::CreateDecoder(InputSource::CreateForURL(url));
    }
    else{
        decoder = Decoder::CreateForURL(url);
    }
    return Play(decoder);
}

I connect my iPhone to Sony PHA-3 DAC through a lightning to micro-USB connector, when playing a dsf  audio, the DSD indicator in PHA-3 not turn light which means no DoP data sent to PHA-3.
am I missing something in code?

**Comment by sbooth** [comment]
I don't see a problem with your code.  Is it possible the iPhone output isn't bit perfect?  Can you try on a desktop Mac to see if it works properly?

**Comment by pzs7602** [comment]
I use SFBAudioEngine.xcodeproj to build a Mac desktop app, and then play a dsf audio, I 've set the audio output of my mac book pro to Sony PHA-3 connected to it via USB, but no sound an be heard. But when play mp3/aiff/aac .... , I can enjoy the music.
![2015-06-05 20 02 16](https://cloud.githubusercontent.com/assets/2361197/8005709/a85933c8-0bbf-11e5-834d-4f1d3f1a6ca8.png)

**Comment by sbooth** [comment]
It looks like sample rate conversion is being performed from 176.4 to 44.1 which would explain why DoP isn't working correctly because the bit pattern would be altered.  Please try setting the DAC's sample rate to match the DSF file's sample rate.

**Comment by pzs7602** [comment]
My DAC is not able to change the sample rate, is it possible to modify the SFBAudioEngine to remain the DSD audio file's format(include sale rate) when playing dsf audio in DoP mode(say, for 2.8224Mhz DSD , when wrapped as DoP to PCM, is 176400Hz )?

**Comment by sbooth** [comment]
`SFBAudioEngine` attempts to do this (see the log message about the input sample rate and decoder format) but the output sample rate normally comes from the device via core audio.  If your device doesn't support sample rate changes (by using `SetDeviceSampleRate()` in `AudioOutput`) you could try setting the output audio unit's `kAudioUnitProperty_SampleRate` on the scope `kAudioUnitScope_Output` within `CoreAudioOutput`.

**Comment by pzs7602** [comment]
solve the problem by :
AVAudioSession *session=[AVAudioSession sharedInstance]; // get audio session
[session setPreferredSampleRate:176400 error:&err]; // request 176400 Hz

this set the preferred sample rate of input and output device to 176400
thanks!

**Comment by eximpression** [comment]
@pzs7602  you run you code on osx but as I know AVAduioSession seem only available on the iOS? how did [session setPreferredSampleRate:176400 error:&err] work?
