### ISSUE TITLE
How to play an audio file from the specified time?

### ISSUE THREAD

**Issue by pzs7602** [sbooth/SFBAudioEngine#57]
I want to play an audio file from the specified time by:
_player->Play((__bridge CFURLRef)url);
_player->seekToTime(time);

but the audio always played from the very begining, but the following code works:
_player->Play((__bridge CFURLRef)url);
[NSNSThread sleepForTimeInterval:0.01];
_player->seekToTime(time);

It seems the seek operation should be fired when the audio begin to playing.
How to do this perfectly? thanks

**Comment by sbooth** [comment]
`Play()` is asynchronous by nature so the sleep is required to allow the background thread time to catch up.  If you want to play from a specified time you can do something like:

    auto d = SFB::Audio::Decoder::CreateForURL((__bridge CFURLRef)url);
    d->Open();
    d->SeekToFrame(d->GetFormat().mSampleRate * time);
    _player->Play(d);

This required a minor change which is commit 85dda73020a97ca182c8683cf1ecead30ba7872d

Alternatively, you can use a `LoopableRegionDecoder` if you don't need to seek before the initial frame you're playing.

**Comment by pzs7602** [comment]
thanks, it works
