### ISSUE TITLE
Insufficient audio in ring buffer

### ISSUE THREAD

**Issue by pzs7602** [sbooth/SFBAudioEngine#58]
After continuously playing several audio files(all wav files), the decoder stopped and the following  info displayed in console:
<Warning>: Insufficient audio in ring buffer: 488 frames available, 1024 requested

I find the ring buffer setup in audio player.cpp:
#define RING_BUFFER_CAPACITY_FRAMES				16384
#define RING_BUFFER_WRITE_CHUNK_SIZE_FRAMES		2048
#define DECODER_THREAD_IMPORTANCE				6

can I adjust some parameter of these to fix the problem? or may be I should do some clean up before each:
player->Play(url);

Thanks

**Comment by sbooth** [comment]
This message is not necessarily an error and is normal during some playback events.  For example, at the end of a file with no next decoder if the number of remaining frames in the file doesn't match the ring buffer size exactly this message will indicate that a portion of the ring buffer was filled with silence.  Or, if the next decoder contains audio at a different sample rate the message will be displayed then as well.

You can adjust the ring buffer sizes in `AudioPlayer` but I'm not convinced that what you're experiencing is a bug.  Does playback glitch or stop earlier than expected?

**Comment by pzs7602** [comment]
I see, if the next audio's sample rate is different, the message will be displayed. The playback can still continue. Thanks!
