### ISSUE TITLE
'AudioFormat.h' file not found

### ISSUE THREAD

**Issue by wooobie** [sbooth/SFBAudioEngine#60]
Hi!
I have problem. When i try build iOS project i get "'AudioFormat.h' file not found" error. Can you help me? 
OSX project is working fine.

**Comment by zbleftover** [comment]
Excuse me, OSX project throws errors that “use of undeclared identifier 'assert'”, even through I add " #include "assert.h" ", it cannot work. How to solve it? Thanks.

**Comment by sbooth** [comment]
What version of Xcode are you using?  Is this your own project or the sample one?

**Comment by lukamate** [comment]
It's sample one and I have Xcode version 6.4.

**Comment by zbleftover** [comment]
Xcode version is 6.4, I use the sample one. I have set Build Settings - Apple LLVM 6.1 - Language - C++, C++ Language Dialect - C++11 and C++ Standard Library - libc++, but is there any extra settings need to complete?

**Comment by sbooth** [comment]
The sample project works correctly for me in Xcode 6.4 with no changes from the current master.  What file is giving the error?

**Comment by zbleftover** [comment]
FLACDecoder.cpp

**Comment by zbleftover** [comment]
![screen shot 2015-07-13 at 8 28 17 pm](https://cloud.githubusercontent.com/assets/12489196/8649545/ebbd72f4-299d-11e5-81d5-b693f64323a3.png)
