### ISSUE TITLE
Feature request: Play sound from memory

### ISSUE THREAD

**Issue by woc2006** [sbooth/SFBAudioEngine#62]
In my case, I need to play sounds multiple times  repeatedly, but SFB always load sound from disk.
Can you provide API like:
```cpp
/**
@Param data  file content bytes
@Param len file content length
*/
bool Play(const char* data, size_t len);
```

**Comment by sbooth** [comment]
I think the best way to accomplish this would be with a `Decoder` subclass.

**Comment by sbooth** [comment]
Please check out https://github.com/sbooth/SFBAudioEngine/tree/memory-input-source and let me know what you think.

**Comment by woc2006** [comment]
![image](https://cloud.githubusercontent.com/assets/1716430/11607552/e8e2ece4-9b85-11e5-8ec5-5ada8539cbe7.png)
Decoder always return null as the screenshot shows

**Comment by sbooth** [comment]
You need to specify the MIME type since there isn't a URL to help infer the type of audio.  Something like this should work:

```
char *buf = /* */;
SInt64 len = /* */;
auto inputSource = SFB::InputSource::CreateWithMemory(buf, len);
auto decoder = SFB::Audio::Decoder::CreateForInputSource(inputSource, CFSTR("audio/flac"));
```

**Comment by woc2006** [comment]
In read
```
auto decoder = SFB::Audio::Decoder::CreateForInputSource(SFB::InputSource::CreateWithMemory(buffer, size, false), mime);
	audios.push_back(decoder.get());
```

In play
```
auto decoder = audios[index];
	SFB::Audio::Decoder::unique_ptr _decoder(decoder);
	SFB::Audio::Player* usePlayer = nullptr;
	
	usePlayer = new SFB::Audio::Player();
	usePlayer->Play(_decoder);
```

And I get the crash in AudioDecoder.h line 205:
```
inline CFURLRef GetURL() const
```

stack:
![image](https://cloud.githubusercontent.com/assets/1716430/11612563/b2f8a1c2-9c3a-11e5-8cb6-f9a2155d65d1.png)

**Comment by sbooth** [comment]
It's hard to tell why the crash is occurring.  What is the type of `audios`- an array of `AudioDecoder *`? I wonder if there is an object lifetime issue.  It looks like you're storing a raw pointer to the decoder you create in read and then instantiating a `unique_ptr` with the raw pointer in play.  How long do you hang on to the original decoder instance?  If the original instance goes out of scope the underlying memory will be reclaimed and you'd still have a pointer to it in `audios`.

**Comment by woc2006** [comment]
Play() is called in another tick.
I fixed my code as you mentioned above, the unique_ptr delete the decoder at the end of the scope.
my latest code is like this:
```
auto decoder = SFB::Audio::Decoder::CreateForInputSource(SFB::InputSource::CreateWithMemory(buffer, size, false), mime);
audios.push_back(decoder.release());
```

and then I can play the audio once, but crashed at the second call to play.
In SFB AudioPlayer.cpp line 763:
```
mDecoderQueue.push_back(std::move(decoder));
```
mDecoderQueue moved decoder pointer and delete it later.
I can't reuse one decoder in current SFB library.

Can you support decoder reuse or should I create new decoder for each play instance?

**Comment by sbooth** [comment]
Right now decoder reuse isn't supported so you'll need to create a new instance.
