### ISSUE TITLE
Did you lost to initialization the 'sRegisteredSubclasses'

### ISSUE THREAD

**Issue by vhikd** [sbooth/SFBAudioEngine#63]
I get all the things done . And I run the project on my iPad. When I play some audio file,the app will not play any thing because the size of 'sRegisteredSubclasses' is 0.The 'AudioDecoder' will never be created.

And I can't find anywhere to initialization this variable.Could you help me to work it out?
Thanks a lot.

**Comment by vhikd** [comment]
In the AudioDecoder create method , I use the following function to solve this problem . And it works for me .


```
if(FLACDecoder::HandlesFilesWithExtension(pathExtension)) {
        unique_ptr decoder(FLACDecoder::CreateDecoder(std::move(inputSource)));
        if(!AutomaticallyOpenDecoders())
            return decoder;
        else {
            if(decoder->Open(error))
                return decoder;
            // Take back the input source for reuse if opening fails
            else
                inputSource = std::move(decoder->mInputSource);
        }
    }
```

**Comment by sbooth** [comment]
There could be an issue with the `constructor` attribute and static time initialization on iOS.  Could you try adding the following code in your `-application: willFinishLaunchingWithOptions:` and see if it fixes the problem with `sRegisteredSubclasses` not getting populated?

```
SFB::Audio::Decoder::RegisterSubclass<SFB::Audio::FLACDecoder>();
```

**Comment by vhikd** [comment]
I have tried with your code. And it solved this problem . Thanks for your reply.
