### ISSUE TITLE
Some audio file couldn't play in background

### ISSUE THREAD

**Issue by vhikd** [sbooth/SFBAudioEngine#65]
Hello,
I had run the project on my iPhone,and play almost all kinds of audio file perfect.But I find some kind of 'aiff' audio file couldn't play in background when the screen darkens.And when the screen brighter the player will continue to play even though the phone doesn't unlock.
And you can get the file in this 'http://pan.baidu.com/s/1mgiyBeo'

Could you help me to find what happened and why the player stop to output the sound.

**Comment by sbooth** [comment]
What was the format of the aiff file? I couldn't download it from the link you provided.

**Comment by vhikd** [comment]
The file information like this :
 Audio stream information
 Encoding format: PCM
 Audio bit rate: 2304 kbps
 Sound channel number: 2 channels
 Number of samples: 48000 Hz
 Audio digits: 24 bits

And I have post it to my server,you can download it from 'https://download.jiankangle.com:8449/dj/THOR2.aiff'.

Thanks for your reply.

**Comment by vhikd** [comment]
Any suggestions to solve this problem?

**Comment by vhikd** [comment]
I solved this problem to initialize the AudioSession before the playing.

***
    OSStatus status;
    AudioSessionInitialize(NULL, NULL, NULL, this);
    UInt32 sessionCategory = kAudioSessionCategory_PlayAndRecord;
    status = AudioSessionSetProperty (kAudioSessionProperty_AudioCategory,
                                      sizeof (sessionCategory),
                                      &sessionCategory);
    
    if (status != kAudioSessionNoError)
    {
        if (status == kAudioServicesUnsupportedPropertyError) {
            LOGGER_ERR("sfb","AudioSessionInitialize failed: unsupportedPropertyError");
        }else if (status == kAudioServicesBadPropertySizeError) {
            LOGGER_ERR("sfb","AudioSessionInitialize failed: badPropertySizeError");
        }else if (status == kAudioServicesBadSpecifierSizeError) {
            LOGGER_ERR("sfb","AudioSessionInitialize failed: badSpecifierSizeError");
        }else if (status == kAudioServicesSystemSoundUnspecifiedError) {
            LOGGER_ERR("sfb","AudioSessionInitialize failed: systemSoundUnspecifiedError");
        }else if (status == kAudioServicesSystemSoundClientTimedOutError) {
            LOGGER_ERR("sfb","AudioSessionInitialize failed: systemSoundClientTimedOutError");
        }else {
            LOGGER_ERR("sfb","AudioSessionInitialize failed! ");
        }
    }
    
    
    AudioSessionSetActive(TRUE);
***

**Comment by sbooth** [comment]
I'm glad this is working now.
