### ISSUE TITLE
Latest version with latest dependency folders doesn’t build

### ISSUE THREAD

**Issue by jwells89** [sbooth/SFBAudioEngine#68]
After doing a fresh clone and fresh download+unarchive of the dependencies tar file, SFBAudioEngine fails to build. It first throws errors in `AddID3TagtoDictionary.cpp` and and `SetXiphCommentFromMetadata.cpp` which are minor and easy to fix, but then you’ll run into a flurry of errors in `MonkeysAudioEncoder.cpp` which will take a little more time to fix.

**Comment by notjosh** [comment]
If you're building for OS X, you can take a look at https://github.com/sbooth/AudioFrameworks/pull/7. I've tried to automate the creation of the dependencies.

(If you're doing iOS, you're out of luck unless you want to contribute that also ;))

**Comment by sbooth** [comment]
macOS dependencies updated.
