### ISSUE TITLE
Could you please add the feature for manually adjust the equalizer?

### ISSUE THREAD

**Issue by vhikd** [sbooth/SFBAudioEngine#71]
Hello,

The audio engine was awesome!
And could you please add the support to manually adjust the equalizer?

**Comment by sbooth** [comment]
Do you want to add an equalizer audio unit and then adjust its settings?

**Comment by vhikd** [comment]
Yes , this is what I want. Any suggestions to make it down?

发自我的 iPhone

**Comment by sbooth** [comment]
You can do something like this to add an equalizer assuming you're using the Core Audio output:

```
try {
    auto& output = dynamic_cast<SFB::Audio::CoreAudioOutput&>(player->GetOutput());
    AudioUnit eqAU;
    if(!output.AddEffect(kAudioUnitSubType_GraphicEQ, kAudioUnitManufacturer_Apple, 0, 0, & eqAU)) {
        // Couldn't add EQ
    }
    else {
        // Set eq parameters, e.g. kGraphicEQParam_NumberOfBands
    }
}
catch(...)
{}
```

Once you have the Audio Unit you can set the values, display the Cocoa UI, etc.

**Comment by vhikd** [comment]
Thanks for your reply. I will try it out and reply to you as soon as possible. 

发自我的 iPhone

**Comment by vhikd** [comment]
Hello,
I can't figure it out .
I get the AudioUnit with the follow codes:
````
AudioComponentDescription EQUnitDescription;
    EQUnitDescription.componentType= kAudioUnitType_Effect;
    EQUnitDescription.componentSubType = kAudioUnitSubType_AUiPodEQ;
    EQUnitDescription.componentManufacturer = kAudioUnitManufacturer_Apple;
    EQUnitDescription.componentFlags = 0;
    EQUnitDescription.componentFlagsMask = 0;
    AudioComponent inputComponent = AudioComponentFindNext(NULL, &EQUnitDescription);
    AudioUnit eqAU;
    AudioComponentInstanceNew(inputComponent, &eqAU);
AudioUnitSetParameter(eqAU, kAudioUnitSubType_BandPassFilter, kAudioUnitScope_Global, 0,
                          gain, 0);
````

Then I call get the output like this:

````
SFB::Audio::Player *_player = [[MSLocalPlayer sharedInstance] getPlayer];
    try {
        auto& output = dynamic_cast<SFB::Audio::CoreAudioOutput&>(_player->GetOutput());
        
        if(!output.AddEffect(kAudioUnitSubType_AUiPodEQ, kAudioUnitManufacturer_Apple, 0, 0, &eqAU)) {
            // Couldn't add EQ
            NSLog(@"add eq fail");
        }
        else {
            // Set eq parameters, e.g. kGraphicEQParam_NumberOfBands
            NSLog(@"good ~ ");
        }
    }
    catch(NSError *error)
    {}
````

The player was playing some `MP3` files .Everything seems to be done,but nothing changed.

After this, I think it must be something wrong with the `effectnode` or something else. So I also try to change the property of the `effectUnit` in the function named `bool SFB::Audio::CoreAudioOutput::AddEffect(OSType componentType, OSType subType, OSType manufacturer, UInt32 flags, UInt32 mask, AudioUnit *effectUnit1)` , but nothing changed else.

Could you please help me to check if I had did something wrong with it.
Thank you very much.

**Comment by sbooth** [comment]
Does the AU add successfully?  If so, what does `CAShow(eqAU)` print out?

**Comment by vhikd** [comment]
The AU did add successfully.
The `CAShow(eqAU)` couldn't print anything.But I call `CAShow(mAUGraph)`.

The original state of `mAUGraph` like this:

```
AudioUnitGraph 0x1891003:
  Member Nodes:
	node 1: 'aumx' 'mcmx' 'appl', instance 0x157068530 O I
	node 2: 'auou' 'rioc' 'appl', instance 0x155ed3300 O I
  Connections:
	node   1 bus   0 => node   2 bus   0  [ 2 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]
  Input Callbacks:
	{0x1000af3dc, 0x155ee0410} => node   1 bus   0  [2 ch, 44100 Hz]
  CurrentState:
	mLastUpdateError=0, eventsToProcess=F, isInitialized=T, isRunning=T (1)
```

After add the `eqAU`,the `mAUGraph` changed to this:

```
AudioUnitGraph 0x1891003:
  Member Nodes:
	node 1: 'aumx' 'mcmx' 'appl', instance 0x157068530 O I
	node 2: 'auou' 'rioc' 'appl', instance 0x155ed3300 O I
	node 3: 'aufx' 'ipeq' 'appl', instance 0x1573a3960 O I
  Connections:
	node   1 bus   0 => node   3 bus   0  [ 2 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]
	node   3 bus   0 => node   2 bus   0  [ 2 ch,  44100 Hz, 'lpcm' (0x00000029) 32-bit little-endian float, deinterleaved]
  Input Callbacks:
	{0x1000af3dc, 0x155ee0410} => node   1 bus   0  [2 ch, 44100 Hz]
  CurrentState:
	mLastUpdateError=0, eventsToProcess=F, isInitialized=T, isRunning=T (1)
```

So , the `eqAU` did add successfully.But nothing changed at all.

**Comment by sbooth** [comment]
It looks like the equalizer was successfully added as node 3.  Perhaps you don't hear a difference because it defaults to a flat curve?  If you set some of the bands manually does that create an audible difference?
