### ISSUE TITLE
How DoPDecoder works with ASIO  on Mac OS?

### ISSUE THREAD

**Issue by vhikd** [sbooth/SFBAudioEngine#72]
I use SFBAudioEngine.xcodeproj to build a Mac desktop app, and then play a dsf audio, but no sound can be heard. 

I modify the codes in AudioPlayer.cpp for using DoPDecoder when playing .dsf audio file:

```
bool SFB::Audio::Player::Play(CFURLRef url)
{
    if(nullptr == url)
        return false;

//  auto decoder = Decoder::CreateForURL(url);
    SFB::CFString extension = CFURLCopyPathExtension(url);
    Decoder::unique_ptr decoder;
    if(kCFCompareEqualTo == CFStringCompare(extension, CFSTR("dsf"), kCFCompareCaseInsensitive)){
        std::cout << "dsf decoder";
        decoder = DoPDecoder::CreateForURL(url);
    }
    else{
        decoder = Decoder::CreateForURL(url);
    }
    return Play(decoder);
}
```

And in my console :

```
Sep  1 16:32:03  [14730] <Info>: Enqueuing "aaa.dff"
Sep  1 16:32:03  [14730] <Info>: Input sample rate (176400) and output sample rate (44100) don't match
Sep  1 16:32:10  [14730] <Info>: Adjusting kAudioUnitProperty_MaximumFramesPerSlice to 2064
Sep  1 16:32:10  [14730] <Info>: Decoding starting for "aaa.dff"
Sep  1 16:32:10  [14730] <Info>: Decoder format: 2 ch, 176400 Hz, 'DoP ' (0x0000002e) 24 bits/channel, 3 bytes/packet, 1 frames/packet, 3 bytes/frame
Sep  1 16:32:10  [14730] <Info>: Decoder channel layout: (null)
Sep  1 16:32:10  [14730] <Debug>: Starting output
```

Then I had tried to change the sample rate like this `SetDeviceSampleRate(inputSampleRate);`
but failed at last:

```
Sep  1 16:34:17  [14820] <Debug>: Setting device sample rate to 176400
Sep  1 16:34:17  [14820] <Error>: AudioObjectSetPropertyData (kAudioDevicePropertyNominalSampleRate) failed: 560226676
```

Could you please help me to check if there is something wrong in the code ?

**Comment by sbooth** [comment]
`DoPDecoder` supports DSD over PCM so it will not work with ASIO output.  In order to use ASIO you'll need to use the DSDIFF or DSF decoders.  `DoPDecoder` just repackages the DSD to appear PCM-like so it can be transmitted, but it requires a special DAC to handle the DoP stream at the other end.  There is no support in `SFBAudioEngine` for actual DSD to PCM conversion.

**Comment by vhikd** [comment]
Thanks for your reply!
I will close the issue soon.
