### ISSUE TITLE
The app will be crashed when play AAC on iOS 11 

### ISSUE THREAD

**Issue by vhikd** [sbooth/SFBAudioEngine#82]
The app can't play music in .m4a format on iOS 11 . And in iOS 10 , it will run well. 
Is there any way to handle this ?

**Comment by sbooth** [comment]
Which app using SFBAudioEngine is having the problem?

**Comment by vhikd** [comment]
The app was not distributed . And I just develop it for my friends and myself. I can send a download url to you . I have updated my device to iOS 11 recently and the app will not working well when play aac music.

I found the app will be crashed when copy the `AudioChannelLayout` . The `AudioChannelLayout` have a really big size. And I think there must be something wrong to calculate the size. But I don't know how to change it.

**Comment by sbooth** [comment]
Can you post some code to reproduce the issue? What data does the `AudioChannelLayout` contain?

**Comment by vhikd** [comment]
I have upload the file to google drive. You can download and test it. It will lead to a crash only on iOS 11 , you should test it on iOS 11.
https://drive.google.com/open?id=16pAEB8ioEtaq4rxxf1GDfu9jHPvwg0n6

**Comment by vhikd** [comment]
Any suggestions to handle this problem ?
