### ISSUE TITLE
Can't compile project

### ISSUE THREAD

**Issue by woko666** [sbooth/SFBAudioEngine#83]
Hello, I'm following the build instruction to the letter:
```
Get the source code: git clone https://github.com/sbooth/SFBAudioEngine.git
Download the dependencies and unpack in the project's root: http://files.sbooth.org/SFBAudioEngine-dependencies.tar.bz2
Open the project and build! (SFBAudioEngine-iOS.xcodeproj)
```

However, when I target a device I get the following compile error: `'wavpack/wavpack.h' file not found`, and when I target simulator I get `'AudioFormat.h' file not found`

Is there anything else that's not in the 3-step guide that I need to do to be able to compile the project?
Cheers!

**Comment by sbooth** [comment]
I need to update the dependencies archive. A while back I switched from using dylibs to static libs in the project and never uploaded them. I will try and take care of that in the next few days.

**Comment by sbooth** [comment]
The dependencies are updated along with the project (deployment target is 10.13).
