### ISSUE TITLE
can‘t build ios project

### ISSUE THREAD

**Issue by xinyu198736** [sbooth/SFBAudioEngine#93]
i git clone the project and put libraries into the project's root then  open SFBAudioEngine-iOS.xcodeproj and build

throw errors like this:

error: Build input file cannot be found: '/Users/yuu/code/SFBAudioEngine/ReplayGainAnalyzer.cpp' (in target 'libSFBAudioEngine' from project 'SFBAudioEngine-iOS')
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'libSFBAudioEngine' from project 'SFBAudioEngine-iOS')

**Comment by xinyu198736** [comment]
![image](https://user-images.githubusercontent.com/897401/78907868-db960c80-7ab3-11ea-8173-bf61de2a334a.png)

some files are gray status

**Comment by xinyu198736** [comment]
when i delete this files 
i got another error
![image](https://user-images.githubusercontent.com/897401/78908147-46474800-7ab4-11ea-92d5-4d3130dbb0c1.png)

**Comment by xinyu198736** [comment]
xcode version Version 11.4 (11E146)

**Comment by sbooth** [comment]
This project is in the midst of large changes to convert the playback implementation from AUGraph to AVAudioEngine. Once the conversion is complete I will take a look at fixing the iOS project- until then it doesn't make sense to update an obsolete .xcodeproj.

**Comment by xinyu198736** [comment]
Well, to give a suggestion, you can open a new branch for refactoring to keep the master branch stable, haha

**Comment by sbooth** [comment]
I did that for the Objective-C decoders...

**Comment by sbooth** [comment]
PR #99 will allow compiling on iOS with the external libraries to follow

**Comment by sbooth** [comment]
In its current state PR #99 builds and plays audio on iOS using Core Audio.

**Comment by xinyu198736** [comment]
thank you very much
