### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by dylancom** [sbooth/SFBAudioEngine#95]
Is there any chance in integrating this as a pod?

**Comment by sbooth** [comment]
This could be done, but so far I haven't because of the dependence on numerous third-party libraries. Since I provide the library binaries as a download anyway it might make sense to provide a podspec.

Once #84 is merged I will take a look at this again.

**Comment by immortal79** [comment]
Hi, are you still considering adding support for cocoapods ? It would be so much easier to use this library.

**Comment by sbooth** [comment]
Reading the [Podspec Syntax Reference](https://guides.cocoapods.org/syntax/podspec.html#specification) it wasn't clear to me how to integrate external pre-built dependencies, although an Xcode run script phase could be a possibility. It may be an indictment of my build system but downloading and compiling the dependencies is a manual process and although an automated process would be nice it doesn't exist currently.

Does anyone with more CocoaPods experience have any suggestions?

**Comment by immortal79** [comment]
Sadly I don't have this kind of experience 😅

**Comment by sbooth** [comment]
I'm closing this issue because I recently updated and simplified the build process which should make it easier to use SFBAudioEngine.
